/**
 * File: stub_pic16f877a.h
 * Autogenerated by SFR Extractor
 *
 * Created on 2021-08-08 11:09:01
 */

#ifndef STUB_PIC16F877A_H
#define STUB_PIC16F877A_H

#define __CLANG__
#define _BV(bit) (1 << (bit))



//char PORTD = 0;
//extern char PORTD = 0;
//char TRISD = 0;
//#include "__at.h"

// Register: INDF
// bitfield definitions
typedef union {
    struct {
        unsigned C                      :1;
        unsigned DC                     :1;
        unsigned Z                      :1;
        unsigned nPD                    :1;
        unsigned nTO                    :1;
        unsigned RP                     :2;
        unsigned IRP                    :1;
    };
    struct {
        unsigned                        :5;
        unsigned RP0                    :1;
        unsigned RP1                    :1;
    };
    struct {
        unsigned CARRY                  :1;
        unsigned                        :1;
        unsigned ZERO                   :1;
    };
 struct {
 unsigned INDF :8;
 };
} STATUSbits_t;
extern volatile STATUSbits_t STATUSbits ;//__at0x003);

// Register: FSR
// bitfield definitions
typedef union {
    struct {
        unsigned RA0                    :1;
        unsigned RA1                    :1;
        unsigned RA2                    :1;
        unsigned RA3                    :1;
        unsigned RA4                    :1;
        unsigned RA5                    :1;
    };
 struct {
 unsigned PORTA :8;
 };
} PORTAbits_t;
extern volatile PORTAbits_t PORTAbits ;//__at0x005);

// Register: PORTB
// bitfield definitions
typedef union {
    struct {
        unsigned RB0                    :1;
        unsigned RB1                    :1;
        unsigned RB2                    :1;
        unsigned RB3                    :1;
        unsigned RB4                    :1;
        unsigned RB5                    :1;
        unsigned RB6                    :1;
        unsigned RB7                    :1;
    };
 struct {
 unsigned PORTB :8;
 };
} PORTBbits_t;
volatile PORTBbits_t PORTBbits ;//__at0x006);

// Register: PORTC
// bitfield definitions
typedef union {
    struct {
        unsigned RC0                    :1;
        unsigned RC1                    :1;
        unsigned RC2                    :1;
        unsigned RC3                    :1;
        unsigned RC4                    :1;
        unsigned RC5                    :1;
        unsigned RC6                    :1;
        unsigned RC7                    :1;
    };
 struct {
 unsigned PORTC :8;
 };
} PORTCbits_t;
extern volatile PORTCbits_t PORTCbits ;//__at0x007);

// // Register: PORTD
// // bitfield definitions
typedef union {
    struct {
        unsigned RD0                    :1;
        unsigned RD1                    :1;
        unsigned RD2                    :1;
        unsigned RD3                    :1;
        unsigned RD4                    :1;
        unsigned RD5                    :1;
        unsigned RD6                    :1;
        unsigned RD7                    :1;
    };
 struct {
 unsigned PORTD :8;
 };
} PORTDbits_t;
volatile PORTDbits_t PORTDbits ;//__at0x008);
//extern int PORTD;
// Register: PORTE
// bitfield definitions
typedef union {
    struct {
        unsigned RE0                    :1;
        unsigned RE1                    :1;
        unsigned RE2                    :1;
    };
 struct {
 unsigned PORTE :8;
 };
} PORTEbits_t;
extern volatile PORTEbits_t PORTEbits ;//__at0x009);

// Register: PCLATH
// bitfield definitions
typedef union {
    struct {
        unsigned PCLATH                 :5;
    };
} PCLATHbits_t;
extern volatile PCLATHbits_t PCLATHbits ;//__at0x00A);

// // Register: INTCON
// // bitfield definitions
typedef union {
    struct {
        unsigned RBIF                   :1;
        unsigned INTF                   :1;
        unsigned TMR0IF                 :1;
        unsigned RBIE                   :1;
        unsigned INTE                   :1;
        unsigned TMR0IE                 :1;
        unsigned PEIE                   :1;
        unsigned GIE                    :1;
    };
    struct {
        unsigned                        :2;
        unsigned T0IF                   :1;
        unsigned                        :2;
        unsigned T0IE                   :1;
    };
 struct {
 unsigned INTCON :8;
 };
} INTCONbits_t;
volatile INTCONbits_t INTCONbits ;//__at0x00B);

#define RBIF INTCONbits.RBIF
#define INTF INTCONbits.INTF
#define TMR0IF INTCONbits.TMR0IF
#define RBIE INTCONbits.RBIE
#define INTE INTCONbits.INTE
#define TMR0IE INTCONbits.TMR0IE
#define PEIE INTCONbits.PEIE
#define GIE INTCONbits.GIE

// Register: PIR1
// bitfield definitions
typedef union {
    struct {
        unsigned TMR1IF                 :1;
        unsigned TMR2IF                 :1;
        unsigned CCP1IF                 :1;
        unsigned SSPIF                  :1;
        unsigned TXIF                   :1;
        unsigned RCIF                   :1;
        unsigned ADIF                   :1;
        unsigned PSPIF                  :1;
    };
 struct {
 unsigned PIR1 :8;
 };
} PIR1bits_t;
extern volatile PIR1bits_t PIR1bits ;//__at0x00C);

// Register: PIR2
// bitfield definitions
typedef union {
    struct {
        unsigned CCP2IF                 :1;
        unsigned                        :2;
        unsigned BCLIF                  :1;
        unsigned EEIF                   :1;
        unsigned                        :1;
        unsigned CMIF                   :1;
    };
 struct {
 unsigned PIR2 :8;
 };
} PIR2bits_t;
extern volatile PIR2bits_t PIR2bits ;//__at0x00D);

// // Register: TMR1
// // bitfield definitions
typedef union {
    struct {
        unsigned TMR1ON                 :1;
        unsigned TMR1CS                 :1;
        unsigned nT1SYNC                :1;
        unsigned T1OSCEN                :1;
        unsigned T1CKPS                 :2;
    };
    struct {
        unsigned                        :2;
        unsigned T1SYNC                 :1;
        unsigned                        :1;
        unsigned T1CKPS0                :1;
        unsigned T1CKPS1                :1;
    };
    struct {
        unsigned                        :2;
        unsigned T1INSYNC               :1;
    };
 struct {
 unsigned TMR1 :8;
 };
} T1CONbits_t;
extern volatile T1CONbits_t T1CONbits;//__at0x010);

// Register: TMR2
// bitfield definitions
typedef union {
    struct {
        unsigned T2CKPS                 :2;
        unsigned TMR2ON                 :1;
        unsigned TOUTPS                 :4;
    };
    struct {
        unsigned T2CKPS0                :1;
        unsigned T2CKPS1                :1;
        unsigned                        :1;
        unsigned TOUTPS0                :1;
        unsigned TOUTPS1                :1;
        unsigned TOUTPS2                :1;
        unsigned TOUTPS3                :1;
    };
 struct {
 unsigned TMR2 :8;
 };
} T2CONbits_t;
extern volatile T2CONbits_t T2CONbits ;//__at0x012);

// Register: SSPBUF
// bitfield definitions
typedef union {
    struct {
        unsigned SSPM                   :4;
        unsigned CKP                    :1;
        unsigned SSPEN                  :1;
        unsigned SSPOV                  :1;
        unsigned WCOL                   :1;
    };
    struct {
        unsigned SSPM0                  :1;
        unsigned SSPM1                  :1;
        unsigned SSPM2                  :1;
        unsigned SSPM3                  :1;
    };
 struct {
 unsigned SSPBUF :8;
 };
} SSPCONbits_t;
extern volatile SSPCONbits_t SSPCONbits ;//__at0x014);

// Register: CCPR1
// bitfield definitions
typedef union {
    struct {
        unsigned CCP1M                  :4;
        unsigned CCP1Y                  :1;
        unsigned CCP1X                  :1;
    };
    struct {
        unsigned CCP1M0                 :1;
        unsigned CCP1M1                 :1;
        unsigned CCP1M2                 :1;
        unsigned CCP1M3                 :1;
    };
 struct {
 unsigned CCPR1 :8;
 };
} CCP1CONbits_t;
extern volatile CCP1CONbits_t CCP1CONbits ;//__at0x017);

// Register: RCSTA
// bitfield definitions
typedef union {
    struct {
        unsigned RX9D                   :1;
        unsigned OERR                   :1;
        unsigned FERR                   :1;
        unsigned ADDEN                  :1;
        unsigned CREN                   :1;
        unsigned SREN                   :1;
        unsigned RX9                    :1;
        unsigned SPEN                   :1;
    };
    struct {
        unsigned RCD8                   :1;
        unsigned                        :5;
        unsigned RC9                    :1;
    };
    struct {
        unsigned                        :6;
        unsigned nRC8                   :1;
    };
    struct {
        unsigned                        :6;
        unsigned RC8_9                  :1;
    };
 struct {
 unsigned RCSTA :8;
 };
} RCSTAbits_t;
volatile RCSTAbits_t RCSTAbits ;//__at0x018);

// Register: TXREG
// bitfield definitions
typedef union {
    struct {
        unsigned CCP2M                  :4;
        unsigned CCP2Y                  :1;
        unsigned CCP2X                  :1;
    };
    struct {
        unsigned CCP2M0                 :1;
        unsigned CCP2M1                 :1;
        unsigned CCP2M2                 :1;
        unsigned CCP2M3                 :1;
    };
 struct {
 unsigned TXREG :8;
 };
} CCP2CONbits_t;
extern volatile CCP2CONbits_t CCP2CONbits ;//__at0x01D);

// Register: ADRESH
// bitfield definitions
typedef union {
    struct {
        unsigned ADON                   :1;
        unsigned                        :1;
        unsigned GO_nDONE               :1;
        unsigned CHS                    :3;
        unsigned ADCS                   :2;
    };
    struct {
        unsigned                        :2;
        unsigned GO                     :1;
        unsigned CHS0                   :1;
        unsigned CHS1                   :1;
        unsigned CHS2                   :1;
        unsigned ADCS0                  :1;
        unsigned ADCS1                  :1;
    };
    struct {
        unsigned                        :2;
        unsigned nDONE                  :1;
    };
    struct {
        unsigned                        :2;
        unsigned GO_DONE                :1;
    };
 struct {
 unsigned ADRESH :8;
 };
} ADCON0bits_t;
extern volatile ADCON0bits_t ADCON0bits ;//__at0x01F);

// Register: OPTION_REG
// bitfield definitions
typedef union {
    struct {
        unsigned PS                     :3;
        unsigned PSA                    :1;
        unsigned T0SE                   :1;
        unsigned T0CS                   :1;
        unsigned INTEDG                 :1;
        unsigned nRBPU                  :1;
    };
    struct {
        unsigned PS0                    :1;
        unsigned PS1                    :1;
        unsigned PS2                    :1;
    };
 struct {
 unsigned OPTION_REG :8;
 };
} OPTION_REGbits_t;
extern volatile OPTION_REGbits_t OPTION_REGbits ;//__at0x081);

// Register: TRISA
// bitfield definitions
typedef union {
    struct {
        unsigned TRISA0                 :1;
        unsigned TRISA1                 :1;
        unsigned TRISA2                 :1;
        unsigned TRISA3                 :1;
        unsigned TRISA4                 :1;
        unsigned TRISA5                 :1;
    };
 struct {
 unsigned TRISA :8;
 };
} TRISAbits_t;
extern volatile TRISAbits_t TRISAbits ;//__at0x085);

// Register: TRISB
// bitfield definitions
typedef union {
    struct {
        unsigned TRISB0                 :1;
        unsigned TRISB1                 :1;
        unsigned TRISB2                 :1;
        unsigned TRISB3                 :1;
        unsigned TRISB4                 :1;
        unsigned TRISB5                 :1;
        unsigned TRISB6                 :1;
        unsigned TRISB7                 :1;
    };
 struct {
 unsigned TRISB :8;
 };
} TRISBbits_t;
extern volatile TRISBbits_t TRISBbits ;//__at0x086);

// Register: TRISC
// bitfield definitions
typedef union {
    struct {
        unsigned TRISC0                 :1;
        unsigned TRISC1                 :1;
        unsigned TRISC2                 :1;
        unsigned TRISC3                 :1;
        unsigned TRISC4                 :1;
        unsigned TRISC5                 :1;
        unsigned TRISC6                 :1;
        unsigned TRISC7                 :1;
    };
 struct {
 unsigned TRISC :8;
 };
} TRISCbits_t;
extern volatile TRISCbits_t TRISCbits ;//__at0x087);

// Register: TRISD
// bitfield definitions
typedef union {
    struct {
        unsigned TRISD0                 :1;
        unsigned TRISD1                 :1;
        unsigned TRISD2                 :1;
        unsigned TRISD3                 :1;
        unsigned TRISD4                 :1;
        unsigned TRISD5                 :1;
        unsigned TRISD6                 :1;
        unsigned TRISD7                 :1;
    };
 struct {
 unsigned TRISD :8;
 };
} TRISDbits_t;
volatile TRISDbits_t TRISDbits ;//__at0x088);
//extern int PORTD;
//extern char TRISD = 0;
// Register: TRISE
// bitfield definitions
typedef union {
    struct {
        unsigned TRISE0                 :1;
        unsigned TRISE1                 :1;
        unsigned TRISE2                 :1;
        unsigned                        :1;
        unsigned PSPMODE                :1;
        unsigned IBOV                   :1;
        unsigned OBF                    :1;
        unsigned IBF                    :1;
    };
 struct {
 unsigned TRISE :8;
 };
} TRISEbits_t;
extern volatile TRISEbits_t TRISEbits ;//__at0x089);

// Register: PIE1
// bitfield definitions
typedef union {
    struct {
        unsigned TMR1IE                 :1;
        unsigned TMR2IE                 :1;
        unsigned CCP1IE                 :1;
        unsigned SSPIE                  :1;
        unsigned TXIE                   :1;
        unsigned RCIE                   :1;
        unsigned ADIE                   :1;
        unsigned PSPIE                  :1;
    };
 struct {
 unsigned PIE1 :8;
 };
} PIE1bits_t;
extern volatile PIE1bits_t PIE1bits ;//__at0x08C);

// Register: PIE2
// bitfield definitions
typedef union {
    struct {
        unsigned CCP2IE                 :1;
        unsigned                        :2;
        unsigned BCLIE                  :1;
        unsigned EEIE                   :1;
        unsigned                        :1;
        unsigned CMIE                   :1;
    };
 struct {
 unsigned PIE2 :8;
 };
} PIE2bits_t;
extern volatile PIE2bits_t PIE2bits ;//__at0x08D);

// Register: PCON
// bitfield definitions
typedef union {
    struct {
        unsigned nBOR                   :1;
        unsigned nPOR                   :1;
    };
    struct {
        unsigned nBO                    :1;
    };
 struct {
 unsigned PCON :8;
 };
} PCONbits_t;
extern volatile PCONbits_t PCONbits ;//__at0x08E);

// Register: SSPCON2
// bitfield definitions
typedef union {
    struct {
        unsigned SEN                    :1;
        unsigned RSEN                   :1;
        unsigned PEN                    :1;
        unsigned RCEN                   :1;
        unsigned ACKEN                  :1;
        unsigned ACKDT                  :1;
        unsigned ACKSTAT                :1;
        unsigned GCEN                   :1;
    };
 struct {
 unsigned SSPCON2 :8;
 };
} SSPCON2bits_t;
extern volatile SSPCON2bits_t SSPCON2bits ;//__at0x091);

// Register: PR2
// bitfield definitions
typedef union {
    struct {
        unsigned BF                     :1;
        unsigned UA                     :1;
        unsigned R_nW                   :1;
        unsigned S                      :1;
        unsigned P                      :1;
        unsigned D_nA                   :1;
        unsigned CKE                    :1;
        unsigned SMP                    :1;
    };
    struct {
        unsigned                        :2;
        unsigned R                      :1;
        unsigned                        :2;
        unsigned D                      :1;
    };
    struct {
        unsigned                        :2;
        unsigned I2C_READ               :1;
        unsigned I2C_START              :1;
        unsigned I2C_STOP               :1;
        unsigned I2C_DATA               :1;
    };
    struct {
        unsigned                        :2;
        unsigned nW                     :1;
        unsigned                        :2;
        unsigned nA                     :1;
    };
    struct {
        unsigned                        :2;
        unsigned nWRITE                 :1;
        unsigned                        :2;
        unsigned nADDRESS               :1;
    };
    struct {
        unsigned                        :2;
        unsigned R_W                    :1;
        unsigned                        :2;
        unsigned D_A                    :1;
    };
    struct {
        unsigned                        :2;
        unsigned READ_WRITE             :1;
        unsigned                        :2;
        unsigned DATA_ADDRESS           :1;
    };
 struct {
 unsigned PR2 :8;
 };
} SSPSTATbits_t;
extern volatile SSPSTATbits_t SSPSTATbits ;//__at0x094);

// Register: TXSTA
// bitfield definitions
typedef union {
    struct {
        unsigned TX9D                   :1;
        unsigned TRMT                   :1;
        unsigned BRGH                   :1;
        unsigned                        :1;
        unsigned SYNC                   :1;
        unsigned TXEN                   :1;
        unsigned TX9                    :1;
        unsigned CSRC                   :1;
    };
    struct {
        unsigned TXD8                   :1;
        unsigned                        :5;
        unsigned nTX8                   :1;
    };
    struct {
        unsigned                        :6;
        unsigned TX8_9                  :1;
    };
 struct {
 unsigned TXSTA :8;
 };
} TXSTAbits_t;
volatile TXSTAbits_t TXSTAbits ;//__at0x098);

// Register: SPBRG
// bitfield definitions
typedef union {
    struct {
        unsigned CM                     :3;
        unsigned CIS                    :1;
        unsigned C1INV                  :1;
        unsigned C2INV                  :1;
        unsigned C1OUT                  :1;
        unsigned C2OUT                  :1;
    };
    struct {
        unsigned CM0                    :1;
        unsigned CM1                    :1;
        unsigned CM2                    :1;
    };
 struct {
 unsigned SPBRG :8;
 };
} CMCONbits_t;
extern volatile CMCONbits_t CMCONbits ;//__at0x09C);

// Register: CVRCON
// bitfield definitions
typedef union {
    struct {
        unsigned CVR                    :4;
        unsigned                        :1;
        unsigned CVRR                   :1;
        unsigned CVROE                  :1;
        unsigned CVREN                  :1;
    };
    struct {
        unsigned CVR0                   :1;
        unsigned CVR1                   :1;
        unsigned CVR2                   :1;
        unsigned CVR3                   :1;
    };
 struct {
 unsigned CVRCON :8;
 };
} CVRCONbits_t;
extern volatile CVRCONbits_t CVRCONbits ;//__at0x09D);

// Register: ADRESL
// bitfield definitions
typedef union {
    struct {
        unsigned PCFG                   :4;
        unsigned                        :2;
        unsigned ADCS2                  :1;
        unsigned ADFM                   :1;
    };
    struct {
        unsigned PCFG0                  :1;
        unsigned PCFG1                  :1;
        unsigned PCFG2                  :1;
        unsigned PCFG3                  :1;
    };
 struct {
 unsigned ADRESL :8;
 };
} ADCON1bits_t;
extern volatile ADCON1bits_t ADCON1bits ;//__at0x09F);

// Register: EEDATA
// bitfield definitions
typedef union {
    struct {
        unsigned RD                     :1;
        unsigned WR                     :1;
        unsigned WREN                   :1;
        unsigned WRERR                  :1;
        unsigned                        :3;
        unsigned EEPGD                  :1;
    };
 struct {
 unsigned EEDATA :8;
 };
} EECON1bits_t;
extern volatile EECON1bits_t EECON1bits ;//__at0x18C);

//char PORTB;
// #define RB0 PORTB.RB0
// #define RB1 PORTB.RB1
// #define RB2 PORTB.RB2
// #define RB3 PORTB.RB3
// #define RB4 PORTB.RB4
// #define RB5 PORTB.RB5
// #define RB6 PORTB.RB6
// #define RB7 PORTB.RB7

// typedef union
// {
//     struct
//     {
//         unsigned RB0 : 1;
//         unsigned RB1 : 1;
//         unsigned RB2 : 1;
//         unsigned RB3 : 1;
//         unsigned RB4 : 1;
//         unsigned RB5 : 1;
//         unsigned RB6 : 1;
//         unsigned RB7 : 1;
//     };
//     struct
//     {
//         unsigned PORTB : 8;
//     };
// } PORTB;
// #define PORTB PORTBbits.PORTB

// typedef union
// {
//     struct
//     {
//         unsigned RB0 : 1;
//         unsigned RB1 : 1;
//         unsigned RB2 : 1;
//         unsigned RB3 : 1;
//         unsigned RB4 : 1;
//         unsigned RB5 : 1;
//         unsigned RB6 : 1;
//         unsigned RB7 : 1;
//     };
//     struct
//     {
//         unsigned PORTB : 8;
//     };
// } PORTBbits_t;
// extern volatile PORTBbits_t PORTBbits;// __at(0x006);
//extern int PORTB;
// #define RB0 PORTBbits.RB0
// #define RB1 PORTBbits.RB1
// #define RB2 PORTBbits.RB2
// #define RB3 PORTBbits.RB3
// #define RB4 PORTBbits.RB4
// #define RB5 PORTBbits.RB5
// #define RB6 PORTBbits.RB6
// #define RB7 PORTBbits.RB7
#define PORTB PORTBbits.PORTB

//char INTCON;
//#define TMR0IE 0x04

#define INDF INDFbits.INDF
#define FSR FSRbits.FSR
#define PORTA PORTAbits.PORTA
#define PORTC PORTCbits.PORTC
#define PORTD PORTDbits.PORTD
#define PORTE PORTEbits.PORTE
#define PCLATH PCLATHbits.PCLATH
#define INTCON INTCONbits.INTCON
#define PIR1 PIR1bits.PIR1
#define PIR2 PIR2bits.PIR2
#define TMR1 TMR1bits.TMR1
#define TMR2 TMR2bits.TMR2
#define SSPBUF SSPBUFbits.SSPBUF
#define CCPR1 CCPR1bits.CCPR1
#define RCSTA RCSTAbits.RCSTA
//#define TXREG TXREGbits.TXREG
#define ADRESH ADRESHbits.ADRESH
#define OPTION_REG OPTION_REGbits.OPTION_REG
#define TRISA TRISAbits.TRISA
#define TRISB TRISBbits.TRISB
#define TRISC TRISCbits.TRISC
#define TRISD TRISDbits.TRISD
#define TRISE TRISEbits.TRISE
#define PIE1 PIE1bits.PIE1
#define PIE2 PIE2bits.PIE2
#define PCON PCONbits.PCON
#define SSPCON2 SSPCON2bits.SSPCON2
#define PR2 PR2bits.PR2
#define TXSTA TXSTAbits.TXSTA
#define SPBRG SPBRGbits.SPBRG
#define CVRCON CVRCONbits.CVRCON
#define ADRESL ADRESLbits.ADRESL
#define EEDATA EEDATAbits.EEDATA


#endif /* STUB_PIC16F877A_H */

